### PR TITLE
Fix/duplicate resolvers

### LINKED ISSUE #32: data._entities elements amount is not correct
While I was exploring absinthe_federation to try to solve the good first issue, I found another bug.

When you query this

```gql
query getAllProducts {
  allProducts {
    createdBy {
      email
      name
    }
    id
  }
}

```

it returns this error

```json
{
  "errors": [
    {
      "message": "Expected \"data._entities\" to contain 2 elements",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Expected \"data._entities\" to contain 2 elements",
            "    at /Users/scott.mingcrypto.com/Code/federation_poc/gateway/node_modules/@apollo/gateway/dist/executeQueryPlan.js:222:27",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
            "    at async executeNode (/Users/scott.mingcrypto.com/Code/federation_poc/gateway/node_modules/@apollo/gateway/dist/executeQueryPlan.js:132:17)",
            "    at async executeNode (/Users/scott.mingcrypto.com/Code/federation_poc/gateway/node_modules/@apollo/gateway/dist/executeQueryPlan.js:120:27)",
            "    at async executeNode (/Users/scott.mingcrypto.com/Code/federation_poc/gateway/node_modules/@apollo/gateway/dist/executeQueryPlan.js:103:40)",
            "    at async /Users/scott.mingcrypto.com/Code/federation_poc/gateway/node_modules/@apollo/gateway/dist/executeQueryPlan.js:29:35",
            "    at async /Users/scott.mingcrypto.com/Code/federation_poc/gateway/node_modules/@apollo/gateway/dist/index.js:126:38",
            "    at async execute (/Users/scott.mingcrypto.com/Code/federation_poc/gateway/node_modules/apollo-server-core/dist/requestPipeline.js:201:20)",
            "    at async processGraphQLRequest (/Users/scott.mingcrypto.com/Code/federation_poc/gateway/node_modules/apollo-server-core/dist/requestPipeline.js:138:28)",
            "    at async processHTTPRequest (/Users/scott.mingcrypto.com/Code/federation_poc/gateway/node_modules/apollo-server-core/dist/runHttpQuery.js:187:30)"
          ]
        }
      }
    }
  ],
  "data": {
    "allProducts": [
      {
        "createdBy": {
          "email": "support@apollographql.com",
          "name": null
        },
        "id": "apollo-federation"
      },
      {
        "createdBy": {
          "email": "support@apollographql.com",
          "name": null
        },
        "id": "apollo-studio"
      }
    ]
  }
}
```

The reason is the `localhost:4002` returns only one elements:

```gql
query ($representations: [_Any!]!) {
  _entities(representations: $representations) {
    ... on User {
      name
      email
    }
  }
}

```

```json
{
    "representations":
    [
        {
            "__typename": "User",
            "email": "support@apollographql.com"
        }
    ]
}
```

You can reproduce the bug with this [repository](https://github.com/scottming/federation_poc/commit/7a8650177a91c5723c2ea94c7616e96c68a479e7#diff-bd96b8670346da6614b182946066640cf52769888c3e9a4eeffd247504a8851eR25)

### PR DESCRIPTION
**Pull request by SvenW**
Fixes #32. So this fixes the issue where entities wasn't resolved if the same id was passed in several times and the underlying resolver func was a regular resolver.

### CODE REVIEW

File: lib/absinthe/federation/schema/entities_field.ex [hunk 1]
```diff
@@ -84,8 +84,14 @@ defmodule Absinthe.Federation.Schema.EntitiesField do
   def call(%{state: :unresolved} = res, _args) do
     resolutions = resolver(res.source, res.arguments, res)
 
-    value =
-      Enum.uniq_by(resolutions, fn %{middleware: [middleware | _remaining_middleware]} = r ->
+    dataloaders =
+      Enum.filter(resolutions, fn %{middleware: [middleware | _remaining_middleware]} ->
```
Comment (scottming) [inline lib/absinthe/federation/schema/entities_field.ex:88]:
```suggestion
      resolutions
      |> Enum.filter(&match?(%{middleware: [{Absinthe.Middleware.Dataloader, _} | _]}, &1))
```

File: lib/absinthe/federation/schema/entities_field.ex [hunk 2]
```diff
@@ -84,8 +84,14 @@ defmodule Absinthe.Federation.Schema.EntitiesField do
...
+        case middleware do
+          {Absinthe.Middleware.Dataloader, {_loader, _fun}} -> true
+          _ -> false
+        end
+      end)
```
Comment (scottming) [inline lib/absinthe/federation/schema/entities_field.ex:93]:
```suggestion
      resolutions
      |> Enum.filter(&match?(%{middleware: [{Absinthe.Middleware.Dataloader, _} | _]}, &1)
```

File: lib/absinthe/federation/schema/entities_field.ex [hunk 3]
```diff
@@ -95,6 +101,17 @@ defmodule Absinthe.Federation.Schema.EntitiesField do
...
         end
       end)
+
+    resolvers =
+      Enum.filter(resolutions, fn %{middleware: [middleware | _remaining_middleware]} ->
+        case middleware do
+          {Absinthe.Middleware.Dataloader, {_loader, _fun}} -> false
+          _ -> true
+        end
+      end)
```
Comment (scottming) [inline lib/absinthe/federation/schema/entities_field.ex:111]:
```suggestion
      resolvers = Enum.reject(resolutions, &match?(%{middleware: [{Absinthe.Middleware.Dataloader, _} | _]}, &1))
```

**Review by scottming — COMMENTED** [review]
I think using the `match?` way will make the code prettier.

**Comment by SvenW** [comment]
> I think using the `match?` way will make the code prettier.

I switched it so that we group on the specific types instead. That way we can be more explicit and only run the dataloaders once per type

**Review by kdawgwilk — APPROVED** [review]

**Review by scottming — APPROVED** [review]

**Review by MrGrinst — APPROVED** [review]
